---
deployment:
  tasks:
    # 1. Set the correct deployment path for your live domain
    - export DEPLOYPATH=/home3/irineashu/public_html/website_7825feb0/
    
    # 2. Install Node dependencies
    - npm install
    
    # 3. Create the production build (Vite/package.json dictates output folder, 
    # but we assume it results in 'docs' based on your commit messages)
    - npm run build 
    
    # 4. Copy the *contents* of the new 'docs' folder to the live site directory
    - /bin/cp -R docs/* $DEPLOYPATH
    
    # 5. Copy .htaccess for React routing
    - /bin/cp .htaccess $DEPLOYPATH
